[package]
name = "common"
version = "0.2.0"
edition = "2021"
license = "MIT"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
chrono = { version = "0.4", features= ["serde"] }
