[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.10", features = [ "json" ]}
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.56"
