name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3.0.2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install trunk
    - name: Build
      run: cd frontend && trunk build --release
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: dist
        publish_dir: frontend/dist
        force_orphan: true
